spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_booking
    username: postgres
    password: onemoretry111

  jpa:
    hibernate:
      ddl-auto: validate       # production-safe
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
